version: "3.4"

volumes:
    astro_node_modules:

services:
    grader-api:
        build: grader-api
        image: grader-api
        restart: "no"
        volumes:
            - ./grader-api/:/app
            - ./app-cache/:/app-cache
        expose:
            - 7777
        depends_on:
            - database
            - flyway
            - redis
        env_file:
            - project.env
        deploy:
            replicas: 2

    grader-ui:
        build: grader-ui
        image: grader-ui
        restart: "no"
        volumes:
            - ./grader-ui/:/app
            - astro_node_modules:/app/node_modules
        expose:
            - 3000
        depends_on:
            - grader-api

    database:
        container_name: database-server
        image: postgres:14.1
        restart: "no"
        env_file:
            - project.env

    flyway:
        image: flyway/flyway:9.11.0-alpine
        depends_on:
            - database
        volumes:
            - ./flyway/sql/:/flyway/sql
        command: -connectRetries=60 -baselineOnMigrate=true migrate
        env_file:
            - project.env

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - grader-api
        ports:
            - "7800:7800"

    redis:
        image: redis:latest
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - ./redif/redif.conf:/usr/local/etc/redis/redis.conf
        expose:
            - 6379